// ─────────────────────────────────────────────
//  RadioFlow AI — Static Data & Constants
// ─────────────────────────────────────────────

/** @type {import('./types').Case[]} */
export const INITIAL_CASES = [
  {
    id: 'RF-0041',
    patient: 'CHEN, Wei',
    age: 67,
    study: 'CT Chest',
    modality: 'CT',
    received: '08:12',
    mrn: 'MRN-884721',
    referrer: 'Dr. Patel, ED',
    indication: 'Shortness of breath, pleuritic chest pain',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
  {
    id: 'RF-0042',
    patient: 'OKONKWO, Adaeze',
    age: 54,
    study: 'CXR PA/LAT',
    modality: 'XR',
    received: '08:34',
    mrn: 'MRN-330458',
    referrer: 'Dr. Mensah, Pulm',
    indication: 'Productive cough, 5 days fever',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
  {
    id: 'RF-0043',
    patient: 'VASQUEZ, Marco',
    age: 29,
    study: 'CT Head',
    modality: 'CT',
    received: '08:51',
    mrn: 'MRN-119034',
    referrer: 'Dr. Kim, Neuro',
    indication: 'MVA, GCS 12, head strike',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
  {
    id: 'RF-0044',
    patient: 'IBRAHIM, Layla',
    age: 72,
    study: 'CT Chest/Abd',
    modality: 'CT',
    received: '09:03',
    mrn: 'MRN-774902',
    referrer: 'Dr. Osei, Surgery',
    indication: 'Post-op day 2, tachycardia, hypoxia',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
  {
    id: 'RF-0045',
    patient: 'PETROV, Dmitri',
    age: 45,
    study: 'CXR PA',
    modality: 'XR',
    received: '09:17',
    mrn: 'MRN-562113',
    referrer: 'Dr. Alvarez, IM',
    indication: 'Annual screening, no acute symptoms',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
  {
    id: 'RF-0046',
    patient: 'NAKAMURA, Yuki',
    age: 38,
    study: 'CT Spine',
    modality: 'CT',
    received: '09:31',
    mrn: 'MRN-209847',
    referrer: 'Dr. Singh, Ortho',
    indication: 'Fall from height, back pain, L-spine tenderness',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
  {
    id: 'RF-0047',
    patient: 'ODUYA, Emeka',
    age: 81,
    study: 'CXR AP',
    modality: 'XR',
    received: '09:44',
    mrn: 'MRN-443667',
    referrer: 'Dr. Rossi, Geriatrics',
    indication: 'Trauma, rib pain, reduced air entry R side',
    priority: null,
    aiStatus: 'pending',
    finding: null,
    confidence: null,
    rationale: null,
    safetyChecks: null,
    highlighted: false,
  },
]

/** @type {import('./types').AIFinding[]} */
export const AI_FINDINGS = [
  {
    finding: 'Tension Pneumothorax',
    priority: 'P1',
    confidence: 97,
    rationale:
      'Large right-sided pneumothorax with mediastinal shift detected. Tracheal deviation noted at 11mm from midline. Hemidiaphragm inversion consistent with tension physiology. Contralateral lung compression >40%. Immediate needle decompression indicated.',
    safetyChecks: [
      'DICOM metadata verified — series complete ✓',
      'History–scan correlation: Dyspnea ↔ PTX confirmed ✓',
      'Laterality cross-check passed (R-side marker validated) ✓',
      'No prior studies available — delta baseline flagged ⚠',
    ],
  },
  {
    finding: 'Pulmonary Embolism (Saddle)',
    priority: 'P1',
    confidence: 94,
    rationale:
      'Bilateral saddle embolus identified at main pulmonary artery bifurcation. RV:LV ratio 1.4 indicating right heart strain. CT-PA protocol confirms massive PE. Clot burden score 22/34. Thrombolysis eligibility criteria met pending haematology review.',
    safetyChecks: [
      'DICOM metadata verified — CT-PA protocol confirmed ✓',
      'Contrast dose validated — 80mL Omnipaque 350 ✓',
      'Renal function check: eGFR 74 mL/min — safe ✓',
      'History–scan correlation: Tachycardia ↔ PE pattern ✓',
    ],
  },
  {
    finding: 'Acute Epidural Haematoma',
    priority: 'P1',
    confidence: 92,
    rationale:
      'Biconvex hyperdense extra-axial collection at right temporal-parietal junction. Maximum thickness 18mm. Midline shift 7mm leftward. Transtentorial herniation risk HIGH. Uncal herniation pattern emerging. Neurosurgical evacuation STAT.',
    safetyChecks: [
      'DICOM metadata verified — non-contrast head CT ✓',
      'History–scan correlation: Head trauma ↔ EDH ✓',
      'Midline shift quantified via automated measurement ✓',
      'No contrast administered — appropriate for acute bleed ✓',
    ],
  },
  {
    finding: 'Vertebral Compression Fracture',
    priority: 'P2',
    confidence: 88,
    rationale:
      'L2 superior endplate compression fracture with 35% anterior height loss. No posterior wall retropulsion. Spinal canal dimensions preserved. Osteoporotic pattern with adjacent Schmorl nodes at L1/L3. TLICS score 2 — conservative management appropriate.',
    safetyChecks: [
      'DICOM metadata verified — CT Lumbar protocol ✓',
      'Bone density algorithm v3.1 applied ✓',
      'No cord compression on scout localiser ✓',
      'Prior imaging comparison: new fracture confirmed ✓',
    ],
  },
  {
    finding: 'Community-Acquired Pneumonia',
    priority: 'P2',
    confidence: 85,
    rationale:
      'Right lower lobe consolidation with air bronchograms. Lobar pattern consistent with bacterial aetiology. No parapneumonic effusion. Cardiac silhouette within normal limits. PSI class III — moderate severity. Recommend empirical antibiotics and clinical correlation with WBC/CRP.',
    safetyChecks: [
      'DICOM metadata verified — PA+LAT projections ✓',
      'History–scan correlation: Fever + cough ↔ RLL consolidation ✓',
      'Pleural space assessment — effusion: absent ✓',
      'Cardiomegaly overlay screen: negative ✓',
    ],
  },
  {
    finding: 'Multiple Rib Fractures',
    priority: 'P2',
    confidence: 82,
    rationale:
      'Posterior right 4th, 5th and 6th rib fractures identified. No pneumothorax on inspiration film. No haemothorax. No flail segment. Trauma mechanism (fall) consistent with fracture pattern. Pain management, incentive spirometry and 6h repeat CXR recommended.',
    safetyChecks: [
      'DICOM metadata verified — AP CXR on inspiration ✓',
      'Pneumothorax overlay: negative on current study ✓',
      'History–scan correlation: Blunt trauma ↔ posterior rib Fx ✓',
      'Rib segmentation algorithm v3.2 applied ✓',
    ],
  },
  {
    finding: 'No Significant Finding',
    priority: 'P3',
    confidence: 96,
    rationale:
      'Bilateral lung fields clear. No consolidation, effusion, or pneumothorax. Cardiac silhouette within normal limits (CTR 0.48). Mediastinum unremarkable. Bony thorax intact. Diaphragms well-defined. No acute cardiopulmonary process identified.',
    safetyChecks: [
      'DICOM metadata verified — series complete ✓',
      'Negative predictive value calibration: 96.1% NPV ✓',
      'History–scan correlation: Screening indication ✓',
      'QA check — image quality score: 94/100 ✓',
    ],
  },
]

export const PRIORITY_CONFIG = {
  P1: {
    label: 'CRITICAL',
    color: '#ef4444',
    bg: 'rgba(239,68,68,0.12)',
    border: 'rgba(239,68,68,0.32)',
    order: 0,
  },
  P2: {
    label: 'URGENT',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.10)',
    border: 'rgba(245,158,11,0.28)',
    order: 1,
  },
  P3: {
    label: 'ROUTINE',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.10)',
    border: 'rgba(16,185,129,0.26)',
    order: 2,
  },
}

export const TRIAGE_STEPS = [
  'Segmenting Anatomy',
  'Classifying Findings',
  'Correlating Clinical History',
  'Calibrating Confidence Scores',
  'Re-ordering Worklist',
]
